[tool.poetry]
name = "command-and-control"
version = "0.1.0"
description = ""
authors = ["Bogomolov, Igor"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
